version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
      
  - package-ecosystem: "nuget"
    directory: "/Source/"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/Source/"
    schedule:
      interval: "daily"
    target-branch: "develop"
