# Docker compose base file for integration tests.
# This compose file is extended by docker-compose.IntegrationTests.{sector}.yml files to compose up and execute integration tests for the sector industry.

services:
  mock-register:
    image: mock-register
    hostname: mock-register
    ports: 
      - "7000:7000"
      - "7001:7001"
      - "7006:7006"
    extra_hosts:
      - "mock-data-holder-integration-tests:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    healthcheck:
      test: wget --no-check-certificate --no-verbose --spider https://localhost:7006/health || exit 1
      timeout: 5s
      interval: 5s
      retries: 50      
    depends_on:
      mssql:
        condition: service_healthy

  mock-data-holder:
    build:
      context: ..
      dockerfile: Dockerfile   
    environment:    
      - ASPNETCORE_ENVIRONMENT=Release
      - CdrAuthServer__AccessTokenExpirySeconds=3600
      - CdrAuthServer__SupportJarmEncryption=false
    depends_on:
      mssql:
        condition: service_healthy
      mock-register:
        condition: service_healthy

  mock-data-holder-integration-tests:
    ports: 
      - "9999:9999"
      - "9998:9998"
      - "9997:9997"
      - "9996:9996"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    depends_on:
      mssql:
        condition: service_healthy
      mock-register:
        condition: service_healthy
      mock-data-holder:
        condition: service_healthy

  mssql:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa{}w0rd2019
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S . -U sa -P "Pa{}w0rd2019" -Q "SELECT 1" -No || exit 1 
      timeout: 5s
      interval: 5s
      retries: 20    
