# Docker compose file used to execute Energy sector integration test suite.
# It extends docker-compose.IntegrationTests.Base.yml which contains sector agnotsic services.

name: mock-data-holder-integration-tests-energy

services:
  mock-register:
    container_name: mock-register-mdhe-int
    extends:
      file: docker-compose.IntegrationTests.Base.yml
      service: mock-register
    extra_hosts:
      - "mock-data-holder-energy-integration-tests:host-gateway"

  mock-data-holder:
    container_name: mock-data-holder-energy-mdhe-int
    image: mock-data-holder-energy
    hostname: mock-data-holder-energy
    extends:
      file: docker-compose.IntegrationTests.Base.yml
      service: mock-data-holder
    build:
      target: "Energy"        
    ports: 
      - "8100:8100"
      - "8101:8101"
      - "8102:8102"
      - "8105:8105"
      - "3100:3100"
    extra_hosts:
      - "mock-data-holder-energy-integration-tests:host-gateway"
    healthcheck:
      test: ((wget --no-check-certificate --no-verbose --spider https://localhost:8105/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:8101/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:3100)) || exit 1
      timeout: 5s
      interval: 5s
      retries: 50 
    
  mock-data-holder-integration-tests:
    container_name: mock-data-holder-energy-integration-tests-mdhe-int
    image: mock-data-holder-integration-tests-energy
    hostname: mock-data-holder-energy-integration-tests
    extends:
      file: docker-compose.IntegrationTests.Base.yml
      service: mock-data-holder-integration-tests    
    build:
      context: ..
      dockerfile: Dockerfile.integration-tests
      args:
        INTEGRATION_TESTS_LOCATION: Energy/CDR.DataHolder.Energy.Tests.IntegrationTests
        FEED_URI: ${FEED_URI}
        FEED_ACCESSTOKEN: ${FEED_ACCESSTOKEN}
    volumes:
      - "./_temp/mock-data-holder-energy-integration-tests/testresults:/testresults"

  mssql:
    container_name: sql-mdhe-int
    extends:
      file: docker-compose.IntegrationTests.Base.yml
      service: mssql
