# Docker compose file used to execute Banking sector integration test suite.
# It extends docker-compose.IntegrationTests.Base.yml which contains sector agnotsic services.

name: mock-data-holder-integration-tests-banking

services:
  mock-register:
    container_name: mock-register-mdhb-int
    extends:
      file: docker-compose.IntegrationTests.Base.yml
      service: mock-register
    extra_hosts:
      - "mock-data-holder-integration-tests:host-gateway"

  mock-data-holder:
    container_name: mock-data-holder-banking-mdhb-int
    image: mock-data-holder
    hostname: mock-data-holder
    extends:
      file: docker-compose.IntegrationTests.Base.yml
      service: mock-data-holder
    build:
      target: "Banking"        
    ports: 
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8005:8005"
      - "3000:3000"
    extra_hosts:
      - "mock-data-holder-integration-tests:host-gateway"
    healthcheck:
      test: ((wget --no-check-certificate --no-verbose --spider https://localhost:8005/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:8001/health) && (wget --no-check-certificate --no-verbose --spider https://localhost:3000)) || exit 1
      timeout: 5s
      interval: 5s
      retries: 50 
    
  mock-data-holder-integration-tests:
    container_name: mock-data-holder-banking-integration-tests-mdhb-int
    image: mock-data-holder-integration-tests-banking
    hostname: mock-data-holder-integration-tests
    extends:
      file: docker-compose.IntegrationTests.Base.yml
      service: mock-data-holder-integration-tests    
    build:
      context: ..
      dockerfile: Dockerfile.integration-tests
      args:
        INTEGRATION_TESTS_LOCATION: Banking/CDR.DataHolder.Banking.Tests.IntegrationTests
        FEED_URI: ${FEED_URI}
        FEED_ACCESSTOKEN: ${FEED_ACCESSTOKEN}
    volumes:
      - "./_temp/mock-data-holder-banking-integration-tests/testresults:/testresults"
 
  mssql:
    container_name: sql-mdhb-int
    extends:
      file: docker-compose.IntegrationTests.Base.yml
      service: mssql
