<Project>
    <PropertyGroup>
        <TargetFrameworkVersion>net10.0</TargetFrameworkVersion>
        <Version>5.0.0</Version>
        <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
        <WarningsNotAsErrors>NU1901;NU1902</WarningsNotAsErrors>
    </PropertyGroup>
</Project>