# Dockerfile for running integration tests
# playwright jammy for .Net 8
FROM mcr.microsoft.com/playwright/dotnet:v1.43.0-jammy as build

ARG INTEGRATION_TESTS_LOCATION

WORKDIR /src
EXPOSE 9999
EXPOSE 9998
EXPOSE 9997
EXPOSE 9996

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

# Credential provider tool
RUN curl -L https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh  | sh

# Copy source
COPY ./Directory.Build.props ./Directory.Build.props
COPY ./.editorconfig ./.editorconfig
COPY . ./

# Install developer certificate
RUN dotnet dev-certs https 

# Install ca certificate
RUN apt-get update && apt-get install -y sudo
RUN sudo cp ./Shared/CDR.DataHolder.Shared.API.Gateway.mTLS/Certificates/ca.crt /usr/local/share/ca-certificates/ca.crt
RUN sudo update-ca-certificates

# Run tests
WORKDIR /src/${INTEGRATION_TESTS_LOCATION}

ARG FEED_ACCESSTOKEN
ARG FEED_URI
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS="{\"endpointCredentials\": [{\"endpoint\":\"${FEED_URI}\", \"username\":\"docker\", \"password\":\"${FEED_ACCESSTOKEN}\"}]}"
RUN echo $VSS_NUGET_EXTERNAL_FEED_ENDPOINTS

RUN dotnet restore
RUN dotnet build --configuration Release

ENTRYPOINT dotnet test --configuration Release --no-build --logger "trx;verbosity=detailed;LogFileName=results.trx;" --results-directory /testresults
