# Dockerfile for running GetDataRecipient integration tests

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
# EXPOSE 9999
# EXPOSE 9998
# EXPOSE 9997
# EXPOSE 9996

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

# Copy source
COPY . ./

# Install developer certificate
RUN dotnet dev-certs https 

# # Install ca certificate
# RUN apt-get update && apt-get install -y sudo
# RUN sudo cp ./CDR.DataHolder.API.Gateway.mTLS/Certificates/ca.crt /usr/local/share/ca-certificates/ca.crt
# RUN sudo update-ca-certificates

# Run tests
WORKDIR /src/CDR.GetDataRecipients.IntegrationTests
RUN dotnet build --configuration Release

ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--no-build", "--logger", "trx;verbosity=detailed;LogFileName=results.trx", "-r", "/testresults"]
