# Dockerfile for running integration tests
FROM mcr.microsoft.com/playwright/dotnet:v1.36.0-focal as build

ARG INTEGRATION_TESTS_LOCATION

WORKDIR /src
EXPOSE 9999
EXPOSE 9998
EXPOSE 9997
EXPOSE 9996

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

# Copy source
COPY . ./

# Install developer certificate
RUN dotnet dev-certs https 

# Install ca certificate
RUN apt-get update && apt-get install -y sudo
RUN sudo cp ./Shared/CDR.DataHolder.Shared.API.Gateway.mTLS/Certificates/ca.crt /usr/local/share/ca-certificates/ca.crt
RUN sudo update-ca-certificates

# Run tests
WORKDIR /src/${INTEGRATION_TESTS_LOCATION}
RUN dotnet build --configuration Release

ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--no-build", "--logger", "trx;verbosity=detailed;LogFileName=results.trx", "-r", "/testresults"]
