# Docker compose for build pipeline

version: '3.8'

services:
  mock-data-holder-unit-tests:
    container_name: mock-data-holder-unit-tests
    image: mock-data-holder-unit-tests
    build:
      context: .
      dockerfile: Dockerfile.unit-tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    volumes:
      - "./_temp/mock-data-holder-unit-tests/testresults:/testresults"
    depends_on:
      mssql:
        condition: service_healthy

  mssql:
    container_name: sql1
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa{}w0rd2019
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S . -U sa -P "Pa{}w0rd2019" -Q "SELECT 1" || exit 1 
      timeout: 10s
      interval: 10s
      retries: 10    
