# Dockerfile for running unit tests

FROM mcr.microsoft.com/dotnet/sdk:8.0-noble AS build
WORKDIR /src
EXPOSE 9999
EXPOSE 9998
EXPOSE 9997
EXPOSE 9996

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

RUN curl -L https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh  | sh

# Copy source
COPY . ./

# Install ca certificate
RUN apt-get update && apt-get install -y sudo
RUN sudo cp ./Shared/CDR.DataHolder.Shared.API.Gateway.mTLS/Certificates/ca.crt /usr/local/share/ca-certificates/ca.crt
RUN sudo update-ca-certificates

# Build tests
WORKDIR /src
ARG FEED_ACCESSTOKEN
ARG FEED_URI
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS="{\"endpointCredentials\": [{\"endpoint\":\"${FEED_URI}\", \"username\":\"docker\", \"password\":\"${FEED_ACCESSTOKEN}\"}]}"
RUN echo $VSS_NUGET_EXTERNAL_FEED_ENDPOINTS
RUN dotnet restore DataHolder.sln
RUN dotnet build DataHolder.sln --configuration Release

# Run tests
ENTRYPOINT ["dotnet", "test", "DataHolder.sln", "--configuration", "Release", "--filter", "Category=UnitTests", "--no-build", "--logger", "trx;verbosity=detailed", "--results-directory", "/testresults"]
