# Dockerfile for running unit tests

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
EXPOSE 9999
EXPOSE 9998
EXPOSE 9997
EXPOSE 9996

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

# Copy source
COPY . ./

# Install ca certificate
RUN apt-get update && apt-get install -y sudo
RUN sudo cp ./Shared/CDR.DataHolder.Shared.API.Gateway.mTLS/Certificates/ca.crt /usr/local/share/ca-certificates/ca.crt
RUN sudo update-ca-certificates

# Build tests
WORKDIR /src
RUN dotnet build DataHolder.sln --configuration Release

# Run tests
ENTRYPOINT ["dotnet", "test", "DataHolder.sln", "--configuration", "Release", "--filter", "UnitTests", "--no-build", "--logger", "trx;verbosity=detailed", "-r", "/testresults"]
