name: Build Docker Image

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*'
    paths-ignore:
      # Any update here needs to be done for
      # - `pull_request` see below
      - '*.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - '.github/stale.yml'
      - 'LICENSE'
      - 'Help/**'
      - 'CertificateManagement/**'
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
    paths-ignore:
    # Any update here needs to be done for
    # - `push`see before
      - '*.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - '.github/stale.yml'
      - 'LICENSE'
      - 'Help/**'
      - 'CertificateManagement/**'

env:
  DOCKER_BANKING_IMAGE: consumerdataright/mock-data-holder
  DOCKER_ENERGY_IMAGE: consumerdataright/mock-data-holder-energy

jobs:
  build-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ./mock-data-holder
    
    - name: Setup Banking Docker Metadata
      id: meta-banking
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ env.DOCKER_BANKING_IMAGE }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Setup Energy Docker Metadata
      id: meta-energy
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ env.DOCKER_ENERGY_IMAGE }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
    
    - name: Setup Docker QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      if: ${{ github.repository_owner == 'ConsumerDataRight' && github.event_name != 'pull_request' }}
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout Authorisation Server (main)
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/checkout@v2
      with:
        repository: consumerdataright/authorisation-server
        ref: 'refs/heads/main'
        path: ./cdr-auth-server

    - name: Checkout Authorisation Server (develop)
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: actions/checkout@v2
      with:
        repository: consumerdataright/authorisation-server
        ref: 'refs/heads/develop'
        path: ./cdr-auth-server

    - name: Copy cdr-auth-server folder into sb-mock-data-holder
      run: |
        cp -r ${{ github.workspace }}/cdr-auth-server ${{ github.workspace }}/mock-data-holder/Source/cdr-auth-server
    
    - name: Build and push Banking Docker image
      id: docker_banking_build
      uses: docker/build-push-action@v2
      with:
        context: ./mock-data-holder/Source
        file: ./mock-data-holder/Source/Dockerfile
        target: Banking
        platforms: linux/amd64,linux/arm64
        push: ${{ github.repository_owner == 'ConsumerDataRight' && github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-banking.outputs.tags }}
        
    - name: Banking Image digest
      run: echo banking ${{ steps.docker_banking_build.outputs.digest }}

    - name: Build and push Energy Docker image
      id: docker_energy_build
      uses: docker/build-push-action@v2
      with:
        context: ./mock-data-holder/Source
        file: ./mock-data-holder/Source/Dockerfile
        target: Energy
        platforms: linux/amd64,linux/arm64
        push: ${{ github.repository_owner == 'ConsumerDataRight' && github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-energy.outputs.tags }}
        
    - name: Energy Image digest
      run: echo energy ${{ steps.docker_energy_build.outputs.digest }}

    - name: Docker Hub Banking Description
      if: ${{ github.repository_owner == 'ConsumerDataRight' && github.ref_name == 'main' }}
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ env.DOCKER_BANKING_IMAGE }}
        enable-url-completion: true
        readme-filepath: ./mock-data-holder/README.md

    - name: Docker Hub Energy Description
      if: ${{ github.repository_owner == 'ConsumerDataRight' && github.ref_name == 'main' }}
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ env.DOCKER_ENERGY_IMAGE }}
        enable-url-completion: true
        readme-filepath: ./mock-data-holder/README.md
