   
name: Test Report

on:
  workflow_run:
    workflows: ['Build and Test']
    types:
      - completed

jobs:
  unit-test-report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Publish Unit Test Report
      uses: dorny/test-reporter@v1
      with:
        artifact: unit-test-results
        name: Unit Tests
        path: '*.trx'
        reporter: dotnet-trx

  banking-integration-test-report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Publish Banking Integration Test Report
      uses: dorny/test-reporter@v1
      with:
        artifact: banking-integration-test-results
        name: Banking Integration Tests
        path: '*.trx'
        reporter: dotnet-trx

  energy-integration-test-report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Publish Energy Integration Test Report
      uses: dorny/test-reporter@v1
      with:
        artifact: energy-integration-test-results
        name: Energy Integration Tests
        path: '*.trx'
        reporter: dotnet-trx
